### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ohyeah521** [chenyoufu/hack-http-headers#1]
Https请求，我可以通过chrome的扩展方式捕获https请求的明文内容吗？

**Comment by youfulife** [comment]
可以的，目前我看了一下头部是可以的，那么内容应该肯定也是可以的。
![https](https://cloud.githubusercontent.com/assets/7324573/3715882/4e96b160-15f9-11e4-83c1-d2ba2f59920c.png)

**Comment by youfulife** [comment]
使用onBeforeRequest事件就可以获得http请求的内容了，但是无法修改
